# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IMZZtBe3HXeo3ucATlSKuGBC8-NoJfTx
"""

inp_file=open('input4_1.txt',"r")
out_file=open('output4_1.txt',"w")
em_list= {}
num= 0
vertice,edge = inp_file. readline().split()
#-----------------------------

vertice= int(vertice)
edge= int(edge)
for a in range(1,vertice+1) :
  em_list.update({a:[] })

for b in range(edge) :
  s= inp_file .readline().split()
  s= [int(x) for x in s]
    
  temp= em_list.get (s[0])
  temp.append (s[1])

#---------------------------------------
for k,v in em_list.items() :
  visit= [k]
  store= [k]
  
  while store :
    t = store.pop(0)
    
    for x in em_list[t] :
      
      if x == k  :
        num=num+1
      if x not in visit :
        visit.append(x)
        
        store.append(x)

if num ==0 :
  out_file.write("NO")
  
else :
  out_file.write("Yes")
#---------------------------
inp_file.close()
out_file.close()