# -*- coding: utf-8 -*-
"""Task04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QupPBbECmgbaDCVxmFvANo6oX8OdfWNy
"""

inp_file= open('input4.txt',"r")
out_file= open('output4.txt',"w")
num= int (inp_file.readline() )

def number_of_ways (num) :  
  if num == 1 :
    return 1
  if num == 2 :
    return 2  
  
  temp =  [0] * (num + 1)
  
  temp[1] = 1
  
  temp[2] = 2
#-----------------------------------  
  for x in range(3, num + 1) :
    
    temp [x] = temp[x - 1] + temp [x - 2]

  return temp[num]

final_output= number_of_ways(num)
#--------------------------------
out_file.write (str (final_output ))
inp_file.close()
out_file.close()