# -*- coding: utf-8 -*-
"""Task01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I2W3JEfBbHa3p8K110AfSlHyLK7ECpdG
"""

def sec_element(no_of_tasks) :
  return no_of_tasks[1]

inp_file=open('input1.txt',"r")
out_file=open('output1.txt',"w")

read_line= int(inp_file.readline() )
empty_lst= []
empty_lst_2= []
#-----------------------
for x in range(read_line) :
  s, e= map(int, inp_file.readline().split())
  
  empty_lst.append((s, e) )

empty_lst.sort( key= sec_element)
end_t = -1
for no_of_tasks in empty_lst :
  
  if no_of_tasks[0] >= end_t :
    
    empty_lst_2.append(no_of_tasks)
    end_t = no_of_tasks[1]
#-----------------------------
out_file.write( str( len( empty_lst_2) ) + "\n")
for no_of_tasks in empty_lst_2 :
  out_file.write(f'{no_of_tasks[0]} {no_of_tasks[1]}\n')
inp_file.close()
out_file.close()