# -*- coding: utf-8 -*-
"""task1_b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BBA0nem1KFvsB37E_HotyWinchlHV5So
"""

inp_file= open ('input1b_2.txt',"r")
out_file= open( 'output1b_2.txt',"w")
vertice1,vertice2= inp_file. readline(). strip(). split(' ')
#-------------------------------

list_1= [0]* (int(vertice1) +1 )
for a in range(int(vertice2) ) :
  save=[int(b) for b in  inp_file.readline().strip().split(" ")]
   
  if list_1[save[0]] == 0 : 
    list_1[save[0]]= [(save[1],save[2])]
  
  else :
    list_1[save[0]]. append((save[1],save[2]))
#--------------------------------
for k in range(int(vertice1)+1) :
  out_file.write(f"{k} :")
  final_out=str(list_1[k])
  out_file.write(f" {final_out[1:-1] } \n")
#----------------
inp_file.close()
out_file.close()