# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Xze9WZy8d7NQtwj1xJtYxPy-SZI-8yo
"""

inp_file=open('input2_3.txt',"r")
out_file=open('output2_3.txt',"w")
list_1=inp_file.readline()
list_1=list_1.split()


num=0
em_dict={}
em_list=[]
c=int(list_1[1])
#------------------------------
while num <c :
  list_2= inp_file.readline()
  list_2= list_2.split()
  new_line= [list_2[1],list_2[0]]
  
  u= list_2[0]
  v= list_2[1]
  u_alt= new_line[0]
  v_alt= new_line[1]
  
  if(u not in em_dict) :
    em_dict[u] = [v]
    
  
  else :
    em_dict[u].append(v)
#--------------------------------------  
  if(u_alt in em_dict):
    em_dict[u_alt].append(v_alt)
  
  else :
    em_dict[u_alt] = [v_alt]    
  num=num+1  
    
#-------------------------------
queue=[]
def BFS(visited,em_dict,s) :  #s=source
  visited.append(s)
  queue. append(s)
  
  
  while queue :
    s=queue.pop(0)
    print(s,end=" ", file=out_file)
    
    for c in em_dict[s] :  
      
      if c not in visited :
        visited.append(c)
        queue.append(c)
                
#-------------------
BFS(em_list,em_dict,"1")
inp_file.close()
out_file.close()