# -*- coding: utf-8 -*-
"""Task03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ngd0S-Ju_U4f51vjOqHG6A1le2ESban
"""

inp_file=open('input3.txt',"r")
out_file=open('output3.txt',"w")

a,b= map(int , inp_file.readline(). split() )
no_of_roads= [tuple(map(int, x.split()) ) for x in inp_file]
total_maintenance_cost= 0

temp = [[] for _ in range(a + 1) ]
for x,y, z in no_of_roads :
  temp[x].append( (y,z))
  
  temp[y].append( (x,z))

store = set()
store.add(1) 

while len(store) < a:
  min_maintenance_cost = float('inf')
  
  min_city = None

  for x in store:
    
    for y, z in temp[x]:
      
      if y not in store and  z < min_maintenance_cost :
        min_maintenance_cost= z
        min_city= y
 
  store.add(min_city)
  
  total_maintenance_cost += min_maintenance_cost
#------------------------------------------ 
out_file.write(str(total_maintenance_cost) )   
inp_file.close()
out_file.close()