# -*- coding: utf-8 -*-
"""task1_a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lx2Qu6yP10t1MtDaxFMFX2uC1C5KTB2j
"""

inp_file= open('input1a_1.txt',"r")
out_file= open('output1a_1.txt',"w")
lst_1=inp_file.readline()
store_str=""
#-----------------------------
lst_1=lst_1.split()

for x in range(len(lst_1)) :
  lst_1[x]= int(lst_1[x])
no_of_vertices=lst_1[0]
no_of_connections=lst_1[1]
nested_list=[]

for y in range( no_of_vertices+1 ) :
  nested_list.append( [0]* ( no_of_vertices+1))
temp=0

while temp < no_of_connections :
  lst_2=inp_file.readline()
  lst_2=lst_2.split()
  
  row=int (lst_2[0] )
  column=int (lst_2[1] )
  
  nested_list[row][column]=int (lst_2[2] )
  temp=temp+1

for a in nested_list :
  
  for value in a :
    store_str=store_str+ str(value)+' '
  
  print(store_str,file=out_file)
  store_str=""

#----------------
inp_file.close()
out_file.close()