# -*- coding: utf-8 -*-
"""Task02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KGexU2gFOIN-ysUa8TZjKBtDapEiUi6O
"""

def root_node(groupof_friends, i) : 
  
  if groupof_friends[i] == i :
    return i
  
  groupof_friends[i] = root_node(groupof_friends, groupof_friends[i])
  return groupof_friends[i]
#--------------------------
def merge(groupof_friends ,temp , i, x) :
  rt_i= root_node (groupof_friends, i)
  rt_x= root_node (groupof_friends, x)
  
  if rt_i != rt_x :
    groupof_friends[rt_i]= rt_x
    temp[rt_x] += temp[rt_i]

inp_file=open('input2.txt',"r")
out_file=open('output2.txt',"w")

x,y = map(int, inp_file.readline().split())
groupof_friends = [n for n in range(x)]
temp= [1] *x 
#---------------------------
for i in range(y):
  
  s, t = map(int, inp_file.readline().split())
  
  merge(groupof_friends,temp, s-1, t-1)
  
  out_file.write(str(temp[root_node(groupof_friends, s-1)]) + '\n')
inp_file.close()
out_file.close()